# Site Info
title: Wire-Subs
tagline: 'Anime Fansub Indonesia'
description: 'Unduh Gratis Anime & PV Subtitle Indonesia'
baseurl: 'http://fansub.wire-subs.com'
url: 'http://fansub.wire-subs.com/'
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss

paginate: 5
paginate_path: '/blog/page-:num'
permalink: /:title/
timezone: Asia/Jakarta
future: true

version: 3.0.0

# About/contact
author:
  name: Wire-Subs
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 2c657388aa34fc38d12c9268cc16b151 # md5 hash of your email address
  contact:
    facebook:  https://facebook.com/WireSubs
    twitter:   https://twitter.com/WireSubs
    email:     http://www.google.com/recaptcha/mailhide/d?k=01umhKxBd4UE68nwA9kgc9pw==&c=IcDG4pGTbc2WExocYyTBtxYwopqqR_KOVS71xNpgqGI=

# Navigation (2nd level links supported)
nav:
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token:  # leave blank if you don't want google analytics
disqus_short_name: 'pdeddy78' # leave blank if you don't want disqus

feed:
  path: atom.xml